fix(events): init EventUser only if actor is defined
Prevents the following TypeError with events of deleted users (aka "ghost"):

```
  File "/path/to/github3/models.py", line 52, in __init__
    self._update_attributes(json)
  File "/path/to/github3/issues/event.py", line 63, in _update_attributes
    self.actor = users.ShortUser(event["actor"], self)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/github3/models.py", line 52, in __init__
    self._update_attributes(json)
  File "/path/to/github3/users.py", line 309, in _update_attributes
    self.avatar_url = user["avatar_url"]

TypeError: 'NoneType' object is not subscriptable
```